var boardmap_org = { 'SB': keymap['S'],   'DB':   keymap['='], 'CH': keymap['\n'],  'MN':  keymap['\t'],
                     'IS20': keymap['3'], 'OS20': keymap['F'], 'D20': keymap['\\'], 'T20': keymap['/'],
                     'IS19': keymap['l'], 'OS19': keymap['9'], 'D19': keymap['n'],  'T19': keymap['A'],
                     'IS18': keymap['s'], 'OS18': keymap['C'], 'D18': keymap['E'],  'T18': keymap['&'],
                     'IS17': keymap['Y'], 'OS17': keymap['m'], 'D17': keymap['$'],  'T17': keymap['f'],
                     'IS16': keymap['e'], 'OS16': keymap['4'], 'D16': keymap['T'],  'T16': keymap['H'],
                     'IS15': keymap['d'], 'OS15': keymap['I'], 'D15': keymap['b'],  'T15': keymap['5'],
                     'IS14': keymap['o'], 'OS14': keymap['L'], 'D14': keymap['*'],  'T14': keymap['_'],
                     'IS13': keymap['U'], 'OS13': keymap['0'], 'D13': keymap['@'],  'T13': keymap['g'],
                     'IS12': keymap['?'], 'OS12': keymap['K'], 'D12': keymap['-'],  'T12': keymap['X'],
                     'IS11': keymap['a'], 'OS11': keymap['1'], 'D11': keymap['r'],  'T11': keymap['D'],
                     'IS10': keymap['t'], 'OS10': keymap['q'], 'D10': keymap['['],  'T10': keymap['%'],
                     'IS09': keymap['i'], 'OS09': keymap['+'], 'D09': keymap['!'],  'T09': keymap['G'],
                     'IS08': keymap['Q'], 'OS08': keymap['R'], 'D08': keymap['P'],  'T08': keymap['c'],
                     'IS07': keymap['.'], 'OS07': keymap['j'], 'D07': keymap['Z'],  'T07': keymap['B'],
                     'IS06': keymap['6'], 'OS06': keymap['W'], 'D06': keymap['O'],  'T06': keymap['p'],
                     'IS05': keymap['2'], 'OS05': keymap[':'], 'D05': keymap['>'],  'T05': keymap['J'],
                     'IS04': keymap['<'], 'OS04': keymap[';'], 'D04': keymap['\''], 'T04': keymap['7'],
                     'IS03': keymap['('], 'OS03': keymap['"'], 'D03': keymap['M'],  'T03': keymap[','],
                     'IS02': keymap['^'], 'OS02': keymap['V'], 'D02': keymap['h'],  'T02': keymap['N'],
                     'IS01': keymap['#'], 'OS01': keymap[']'], 'D01': keymap['k'],  'T01': keymap['8'] };
